version: '3'
services:
  database:
    image: postgres:latest
    ports:
      - 5555:5432
    restart: always
    environment:
      - POSTGRES_DB=PRO_mrfridge_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
