spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5555/PRO_mrfridge_database
    username: postgres
    password: postgres
